name: Build and Deploy to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
        default: 'aws-cli'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set IMAGE_NAME variable with priority (dispatch > repo env > default)
        run: |
          echo "IMAGE_NAME=${{ github.event.inputs.image_name || env.IMAGE_NAME || 'aws-cli' }}" >> $GITHUB_ENV

      - name: Show chosen image name
        run: echo "Using image name $IMAGE_NAME"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (latest & stable)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/python311:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/python311:stable
